site_name: how-tos
site_description: How-To Articles for Red Hat Developer Hub
site_author: user:evanshortiss
nav:
  - "Overview": index.md
  - "Install Red Hat Developer Hub": install-rhdh.md
  - "Onboarding Applications": onboarding.md
plugins:
  - techdocs-core
